import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./_components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ddd3c8",
        "primary-fixed-dim": "#ddd2ce",
        "on-error-container": "#742410",
        error: "#9e422c",
        "on-tertiary": "#fff8f0",
        "on-primary-container": "#57504d",
        "error-dim": "#5c1202",
        "on-secondary-container": "#575149",
        "on-primary-fixed-variant": "#615a57",
        "on-surface": "#363322",
        "on-tertiary-fixed-variant": "#696255",
        "surface-variant": "#e9e3c9",
        "on-secondary-fixed-variant": "#615a52",
        "on-tertiary-container": "#5e584b",
        "inverse-on-surface": "#a09d93",
        "tertiary-dim": "#595246",
        "on-tertiary-fixed": "#4c463a",
        "secondary-fixed": "#ebe1d6",
        "on-primary-fixed": "#443e3b",
        "secondary-dim": "#59524a",
        "surface-container-highest": "#e9e3c9",
        tertiary: "#655e51",
        background: "#fef9ed",
        "on-background": "#363322",
        outline: "#7f7b66",
        secondary: "#655e56",
        "on-error": "#fff7f6",
        "surface-container-low": "#f9f3e4",
        "inverse-surface": "#0f0e08",
        "surface-tint": "#645d59",
        "surface-container": "#f4eedb",
        "primary-container": "#ebe0dc",
        "on-secondary": "#fff8f2",
        "primary-fixed": "#ebe0dc",
        "secondary-container": "#ebe1d6",
        "on-surface-variant": "#635f4c",
        surface: "#fef9ed",
        "primary-dim": "#58514e",
        "tertiary-container": "#f7eddc",
        "inverse-primary": "#fffbff",
        "surface-container-lowest": "#ffffff",
        primary: "#645d59",
        "surface-container-high": "#eee8d2",
        "error-container": "#fe8b70",
        "on-primary": "#fff6f2",
        "tertiary-fixed-dim": "#e9dece",
        "on-secondary-fixed": "#453e37",
        "tertiary-fixed": "#f7eddc",
        "outline-variant": "#b8b29b",
        "surface-bright": "#fef9ed",
        "surface-dim": "#e1dabe",
      },
      fontFamily: {
        "space-grotesk": ["var(--font-space-grotesk)", "sans-serif"],
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-space-grotesk)", "sans-serif"],
        label: ["var(--font-space-grotesk)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      keyframes: {
        "spin-reverse": {
          from: { transform: "rotate(360deg)" },
          to: { transform: "rotate(0deg)" },
        },
      },
      animation: {
        "spin-reverse": "spin-reverse 90s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
